"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import configparser
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 项目自定义配置统一存放于 config/config.ini（裸键值对 + [deploy] 生产部署节）
_CONFIG_PATH = BASE_DIR / 'config' / 'config.ini'
_parser = configparser.ConfigParser()
_parser.read_string('[default]\n' + _CONFIG_PATH.read_text(encoding='utf-8'))
DEPLOY_ENV = _parser.get('deploy', 'env', fallback='dev').strip().lower()
_IS_PROD = DEPLOY_ENV == 'prod'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = (
    _parser.get('deploy', 'secret_key', fallback='').strip()
    if _IS_PROD
    else 'django-insecure-2sgct1c$7t=ygmf(#n*&lb!bp!fg_6dwu^&7-5jfvv$8&aw@7d'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not _IS_PROD

ALLOWED_HOSTS = (
    [h.strip() for h in _parser.get('deploy', 'allowed_hosts', fallback='').split(',') if h.strip()]
    if _IS_PROD
    else ['*']
)

if _IS_PROD:
    # 生产环境：HTTPS 域名白名单（CSRF 校验来源），与 ALLOWED_HOSTS 一致
    CSRF_TRUSTED_ORIGINS = [f'https://{host}' for host in ALLOWED_HOSTS]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'foodmap',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if _IS_PROD:
    # 生产环境使用 MySQL（服务器自建或 RDS），连接参数在 config.ini [deploy] 配置
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': _parser.get('deploy', 'db_name', fallback='foodmap'),
            'USER': _parser.get('deploy', 'db_user', fallback='foodmap'),
            'PASSWORD': _parser.get('deploy', 'db_password', fallback=''),
            'HOST': _parser.get('deploy', 'db_host', fallback='127.0.0.1'),
            'PORT': _parser.get('deploy', 'db_port', fallback='3306'),
            'OPTIONS': {'charset': 'utf8mb4'},
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # 生产 collectstatic 产物（Nginx 直接服务）

# 用户上传的用餐照片（多图）
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
