# Generated by Django 4.2.30 on 2026-08-06 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='区名')),
                ('adcode', models.CharField(max_length=10, unique=True, verbose_name='行政区代码')),
            ],
            options={
                'verbose_name': '行政区',
                'verbose_name_plural': '行政区',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='餐厅名称')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='foodmap.district', verbose_name='所属区')),
            ],
            options={
                'verbose_name': '餐厅',
                'verbose_name_plural': '餐厅',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='用餐日期')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 星'), (2, '2 星'), (3, '3 星'), (4, '4 星'), (5, '5 星')], default=4, verbose_name='评分')),
                ('comment', models.TextField(blank=True, verbose_name='点评/回忆')),
                ('per_capita', models.PositiveIntegerField(blank=True, null=True, verbose_name='人均消费(元)')),
                ('mood', models.CharField(blank=True, max_length=50, verbose_name='心情标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='foodmap.restaurant', verbose_name='餐厅')),
            ],
            options={
                'verbose_name': '用餐记录',
                'verbose_name_plural': '用餐记录',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
