# Generated by Django 4.2.30 on 2026-08-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmap', '0004_diningrecordphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplashImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='标题')),
                ('image', models.ImageField(upload_to='splash/', verbose_name='图片')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '加载页图片',
                'verbose_name_plural': '加载页图片',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SplashState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_date', models.CharField(blank=True, max_length=10, verbose_name='上次展示日期')),
                ('last_id', models.IntegerField(blank=True, null=True, verbose_name='上次展示图片ID')),
            ],
            options={
                'verbose_name': '加载页状态',
                'verbose_name_plural': '加载页状态',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('category', models.CharField(default='历史故事', max_length=50, verbose_name='分类')),
                ('content', models.TextField(verbose_name='内容')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='story_covers/', verbose_name='封面图')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='来源/作者')),
                ('enabled', models.BooleanField(default=True, verbose_name='上架')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '故事',
                'verbose_name_plural': '故事',
                'ordering': ['-updated_at'],
            },
        ),
    ]
