# Generated by Django 4.2.30 on 2026-08-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmap', '0005_splashimage_splashstate_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='配置键')),
                ('value', models.CharField(blank=True, default='', max_length=1000, verbose_name='配置值')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='说明')),
            ],
            options={
                'verbose_name': 'APP配置',
                'verbose_name_plural': 'APP配置',
                'ordering': ['id'],
            },
        ),
    ]
