# Generated by Django 4.2.30 on 2026-08-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodmap', '0006_appconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
