# Generated by Django 4.2.30 on 2026-08-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmap', '0007_delete_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='标识')),
                ('name', models.CharField(max_length=50, verbose_name='菜名')),
                ('category', models.CharField(db_index=True, max_length=20, verbose_name='菜系/分类')),
                ('description', models.TextField(blank=True, verbose_name='专属文案')),
                ('ingredients', models.TextField(blank=True, help_text='每行一条，如「牛腩 500 克」', verbose_name='材料用量')),
                ('steps', models.TextField(blank=True, help_text='每行一步', verbose_name='制作方法')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='成品图')),
                ('sort', models.IntegerField(default=0, help_text='数字越小越靠前，决定每日轮换顺序', verbose_name='排序')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '每日美食',
                'verbose_name_plural': '每日美食',
                'ordering': ['sort', 'id'],
            },
        ),
    ]
