# Generated by Django 4.2.30 on 2026-08-13 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodmap', '0008_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('dish', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='foodmap.dish', verbose_name='菜品')),
            ],
            options={
                'verbose_name': '美食收藏',
                'verbose_name_plural': '美食收藏',
                'ordering': ['-created_at'],
            },
        ),
    ]
