# Generated by Django 4.2.30 on 2026-08-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmap', '0009_favoritedish'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cost',
            field=models.FloatField(blank=True, null=True, verbose_name='人均消费(元)'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='photos',
            field=models.TextField(blank=True, help_text='JSON 数组 [{"title","url"}]，推荐官卡片用', verbose_name='门店照片'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tag',
            field=models.CharField(blank=True, help_text='高德 tag 字段，逗号分隔', max_length=300, verbose_name='特色菜标签'),
        ),
    ]
