# Generated by Django 4.2.30 on 2026-08-13 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodmap', '0010_restaurant_cost_restaurant_photos_restaurant_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名字')),
                ('breed', models.CharField(blank=True, max_length=50, verbose_name='品种')),
                ('gender', models.CharField(blank=True, choices=[('male', '公'), ('female', '母')], max_length=10, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('adopt_date', models.DateField(blank=True, null=True, verbose_name='来家纪念日')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='pet_avatars/', verbose_name='头像')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '宠物档案',
                'verbose_name_plural': '宠物档案',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PetPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pet_photos/%Y/%m/', verbose_name='照片')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='foodmap.pet', verbose_name='宠物')),
            ],
            options={
                'verbose_name': '宠物照片',
                'verbose_name_plural': '宠物照片',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('vaccine', '疫苗'), ('deworm', '驱虫'), ('weight', '体重'), ('other', '其他')], max_length=10, verbose_name='类型')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('date', models.DateField(verbose_name='日期')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='下次到期')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='体重(kg)')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='foodmap.pet', verbose_name='宠物')),
            ],
            options={
                'verbose_name': '宠物事项',
                'verbose_name_plural': '宠物事项',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
