# Generated by Django 4.2 on 2026-08-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmap', '0011_pet_petphoto_petevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='餐厅名称'),
        ),
        migrations.AddIndex(
            model_name='diningrecord',
            index=models.Index(fields=['restaurant', 'date'], name='record_rest_date_idx'),
        ),
        migrations.AddIndex(
            model_name='diningrecord',
            index=models.Index(fields=['-date'], name='record_date_idx'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='餐厅名称'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='status',
            field=models.CharField(
                choices=[('pending', '待尝'), ('eaten', '已尝')],
                db_index=True,
                default='pending',
                max_length=10,
                verbose_name='状态',
            ),
        ),
    ]
