# Generated by Django 4.2.30 on 2026-08-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmap', '0012_restaurant_name_idx_diningrecord_indexes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Divination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='占卜日期')),
                ('card_name', models.CharField(max_length=50, verbose_name='塔罗牌')),
                ('orientation', models.CharField(max_length=10, verbose_name='牌向')),
                ('keyword', models.CharField(blank=True, max_length=100, verbose_name='关键词')),
                ('reading', models.TextField(blank=True, verbose_name='今日解读')),
                ('lucky', models.CharField(blank=True, max_length=200, verbose_name='幸运指引')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
            ],
            options={
                'verbose_name': '每日占卜',
                'verbose_name_plural': '每日占卜',
                'ordering': ['-date'],
            },
        ),
    ]
