# Generated by Django 4.2.30 on 2026-08-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmap', '0013_divination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('text', models.CharField(max_length=300, verbose_name='金句')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('source', models.CharField(max_length=100, verbose_name='出处')),
                ('category', models.CharField(blank=True, max_length=20, verbose_name='分类')),
                ('image_keyword', models.CharField(blank=True, max_length=50, verbose_name='配图关键词')),
                ('image_url', models.CharField(blank=True, max_length=300, verbose_name='配图链接')),
                ('uuid', models.CharField(blank=True, max_length=36, verbose_name='一言UUID')),
                ('detail_url', models.CharField(blank=True, max_length=200, verbose_name='详情链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '好句好段',
                'verbose_name_plural': '好句好段',
                'ordering': ['-date'],
            },
        ),
    ]
