# Generated by Django 4.2.30 on 2026-08-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmap', '0014_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('name', models.CharField(max_length=50, verbose_name='菜名')),
                ('category', models.CharField(blank=True, max_length=20, verbose_name='分类')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('ingredients', models.TextField(blank=True, help_text='JSON 数组字符串', verbose_name='材料')),
                ('steps', models.TextField(blank=True, help_text='JSON 数组字符串', verbose_name='步骤')),
                ('image_url', models.CharField(blank=True, help_text='相对路径 /media/meals/...', max_length=300, verbose_name='成品图')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
            ],
            options={
                'verbose_name': '每日菜单',
                'verbose_name_plural': '每日菜单',
                'ordering': ['-date'],
            },
        ),
    ]
