# Generated by Django 4.2.30 on 2026-08-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmap', '0015_dailymeal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='取首条用户消息前 30 字', max_length=50, verbose_name='标题')),
                ('messages', models.JSONField(blank=True, default=list, verbose_name='消息列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '推荐官会话',
                'verbose_name_plural': '推荐官会话',
                'ordering': ['-updated_at'],
            },
        ),
    ]
