# Generated by Django 4.2.30 on 2026-08-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmap', '0018_favoritedish_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritedish',
            name='name',
            field=models.CharField(max_length=100, verbose_name='菜名'),
        ),
    ]
