# Generated by Django 4.2.30 on 2026-09-10 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodmap', '0019_alter_favoritedish_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述/文案')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='分类')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_completed', models.BooleanField(default=False, verbose_name='已体验')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='体验日期')),
                ('memory_text', models.TextField(blank=True, verbose_name='回忆日记')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '心愿清单',
                'verbose_name_plural': '心愿清单',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BucketPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bucket_photos/%Y/%m/', verbose_name='照片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='foodmap.bucketitem', verbose_name='心愿')),
            ],
            options={
                'verbose_name': '心愿照片',
                'verbose_name_plural': '心愿照片',
                'ordering': ['id'],
            },
        ),
    ]
