# Generated by Django 4.2.30 on 2026-09-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmap', '0023_alter_appconfig_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('daily_question', '每日一问'), ('this_or_that', '二选一')], db_index=True, max_length=20, verbose_name='题型')),
                ('content', models.TextField(blank=True, verbose_name='题目 / 题干')),
                ('option_a', models.CharField(blank=True, max_length=100, verbose_name='选项 A')),
                ('option_b', models.CharField(blank=True, max_length=100, verbose_name='选项 B')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '游戏题库',
                'verbose_name_plural': '游戏题库',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('daily_question', '每日一问'), ('this_or_that', '二选一'), ('draw_guess', '你画我猜')], db_index=True, max_length=20, verbose_name='游戏')),
                ('date', models.DateField(blank=True, db_index=True, help_text='每日一问按天自动建会话；其他游戏为空', null=True, verbose_name='所属日期')),
                ('state', models.JSONField(default=dict, verbose_name='状态')),
                ('status', models.CharField(choices=[('waiting', '等待开始'), ('active', '进行中'), ('completed', '已完成'), ('abandoned', '已放弃')], default='active', max_length=12, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '游戏会话',
                'verbose_name_plural': '游戏会话',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['game_type', 'status'], name='foodmap_gam_game_ty_7103df_idx')],
            },
        ),
    ]
