# Generated by Django 4.2.30 on 2026-08-06 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodmap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='餐厅名称')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='推荐理由')),
                ('per_capita', models.PositiveIntegerField(blank=True, null=True, verbose_name='人均消费(元)')),
                ('status', models.CharField(choices=[('pending', '待尝'), ('eaten', '已尝')], default='pending', max_length=10, verbose_name='状态')),
                ('source', models.CharField(choices=[('ai', 'AI 推荐'), ('manual', '手动添加')], default='ai', max_length=10, verbose_name='来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlist_items', to='foodmap.district', verbose_name='所属区')),
            ],
            options={
                'verbose_name': '待尝餐厅',
                'verbose_name_plural': '待尝餐厅',
                'ordering': ['-created_at'],
            },
        ),
    ]
