# Generated by Django 4.2.30 on 2026-08-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmap', '0002_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='amap_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='高德POI ID'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='高德评分'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='amap_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='高德POI ID'),
        ),
    ]
