# Generated by Django 4.2.30 on 2026-08-06 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodmap', '0003_restaurant_amap_id_restaurant_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningRecordPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='record_photos/%Y/%m/', verbose_name='照片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='foodmap.diningrecord', verbose_name='用餐记录')),
            ],
            options={
                'verbose_name': '用餐照片',
                'verbose_name_plural': '用餐照片',
                'ordering': ['id'],
            },
        ),
    ]
