# -*- coding: utf-8 -*-
"""完整美食库（80 道）：每道含菜名、菜系、专属文案、材料用量、制作方法与成品图。

前 40 道 = 原内置库（slug 与文案保持不变，补全材料与步骤）；
后 40 道 = 新增菜式（文案由 DeepSeek 生成后填入）。

用途：
- seed_dishes 命令导入数据库（Admin 可运营）
- 同步脚本生成 APP 内置库 app/lib/data/dishes.dart（纯本地模式兜底）
两处数据同序同模，保证云端/本地同一天推荐同一道菜（md5(日期) 取模）。
"""

DISHES_FULL = [
    {
        'slug': 'tomato-beef',
        'name': '番茄牛腩煲',
        'category': '家常菜',
        'description': '酸酸甜甜的番茄把牛腩炖得软烂，就像我想把日子过得又暖又甜。第一次想带你吃的，就是这一锅，连汤都想让你拌饭。',
        'ingredients': '牛腩 500 克\n番茄 3 个\n土豆 1 个\n洋葱 半个\n姜 3 片\n八角 2 颗\n生抽 2 勺\n番茄酱 1 勺\n冰糖 10 克\n盐 适量',
        'steps': '1. 牛腩切块冷水下锅，加料酒姜片焯水，撇去浮沫捞出。\n2. 热油下冰糖炒出糖色，倒入牛腩翻炒上色。\n3. 加番茄块炒出沙，放番茄酱、生抽和热水没过牛肉。\n4. 加八角，小火炖 1 小时至牛腩软烂。\n5. 下土豆和洋葱再炖 15 分钟，收汁调味出锅。',
        'image_url': 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'mapo-tofu',
        'name': '麻婆豆腐',
        'category': '川菜',
        'description': '麻辣鲜香的豆腐，滑嫩得像会跳舞。川菜的魅力就是敢爱敢恨，和它一样，我对你也是明明白白的喜欢。',
        'ingredients': '嫩豆腐 1 盒\n猪肉末 100 克\n豆瓣酱 2 勺\n花椒粉 1 小勺\n姜蒜末 适量\n生抽 1 勺\n淀粉 1 勺\n葱花 适量',
        'steps': '1. 豆腐切块，淡盐水焯一下去豆腥，捞出备用。\n2. 热油炒香肉末，加豆瓣酱和姜蒜末炒出红油。\n3. 加半碗水和生抽，轻轻推入豆腐煮 3 分钟。\n4. 淀粉分两次勾芡，轻推至汤汁浓稠。\n5. 出锅撒花椒粉和葱花。',
        'image_url': 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'sweet-sour-ribs',
        'name': '糖醋排骨',
        'category': '家常菜',
        'description': '酸甜适口，外酥里嫩，是很多人心里家的味道。希望我们的故事，也像它一样甜得刚刚好，不腻不淡。',
        'ingredients': '排骨 500 克\n冰糖 30 克\n香醋 3 勺\n生抽 2 勺\n料酒 1 勺\n姜片 3 片\n熟白芝麻 少许',
        'steps': '1. 排骨冷水下锅焯水，捞出沥干。\n2. 热油小火炒冰糖至琥珀色，倒排骨裹匀糖色。\n3. 加姜片、生抽、料酒和热水没过排骨，小火炖 30 分钟。\n4. 大火收汁时烹入香醋，翻炒至汤汁挂在排骨上。\n5. 撒白芝麻出锅。',
        'image_url': 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'braised-pork',
        'name': '红烧肉',
        'category': '家常菜',
        'description': '肥而不腻、入口即化，是深夜想起就会馋的那一口。以后想给你做一次，看你吃得满足的样子。',
        'ingredients': '五花肉 600 克\n冰糖 25 克\n生抽 2 勺\n老抽 1 勺\n料酒 2 勺\n姜 4 片\n八角 2 颗\n香叶 2 片\n开水 适量',
        'steps': '1. 五花肉切麻将块，冷水下锅焯水后捞出。\n2. 少油小火炒冰糖至枣红色，下肉块翻炒上色。\n3. 加姜片、八角、香叶、生抽、老抽、料酒炒香。\n4. 加开水没过肉块，小火炖 40 分钟。\n5. 大火收汁至油亮浓稠出锅。',
        'image_url': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'steamed-fish',
        'name': '清蒸鲈鱼',
        'category': '粤菜',
        'description': '一条新鲜的鲈鱼，蒸八分钟，淋上热油豉油，鲜到眉毛都要掉。粤菜讲究原汁原味，就像喜欢你也无需修饰。',
        'ingredients': '鲈鱼 1 条（约 600 克）\n姜 1 块\n小葱 3 根\n蒸鱼豉油 3 勺\n食用油 2 勺\n料酒 1 勺\n盐 少许',
        'steps': '1. 鲈鱼处理干净，两面划刀，抹料酒和少许盐腌 10 分钟。\n2. 鱼身铺姜丝葱段，水开后大火蒸 8 分钟。\n3. 出锅倒掉蒸鱼汁，去掉旧姜葱。\n4. 铺上新的葱丝，淋蒸鱼豉油。\n5. 热油浇在葱丝上激出香味。',
        'image_url': 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'kungpao-chicken',
        'name': '宫保鸡丁',
        'category': '川菜',
        'description': '花生酥脆、鸡丁滑嫩、辣中带甜。酸甜辣的平衡最难掌握，而我想和你平衡好每一个普通的日子。',
        'ingredients': '鸡腿肉 300 克\n炸花生米 80 克\n干辣椒 8 个\n花椒 1 小把\n大葱 1 根\n生抽 2 勺\n香醋 2 勺\n白糖 1 勺\n淀粉 1 勺',
        'steps': '1. 鸡腿肉切丁，加生抽和淀粉抓匀腌 15 分钟。\n2. 调碗汁：生抽、香醋、白糖、淀粉加少许水拌匀。\n3. 热油下鸡丁滑炒至变色盛出。\n4. 干辣椒花椒爆香，回锅鸡丁和葱段翻炒。\n5. 倒碗汁快速翻炒，裹匀后撒花生米出锅。',
        'image_url': 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'yuxiang-shredded-pork',
        'name': '鱼香肉丝',
        'category': '川菜',
        'description': '没有鱼却有鱼香，这是川菜最浪漫的误会。就像我遇到你之前，从没想过会为一个人这么心动。',
        'ingredients': '猪里脊 250 克\n水发木耳 50 克\n胡萝卜 半根\n青椒 1 个\n泡椒 3 个\n姜蒜末 适量\n生抽 2 勺\n香醋 2 勺\n白糖 1 勺半\n淀粉 1 勺',
        'steps': '1. 肉丝加生抽和淀粉抓匀腌制，木耳胡萝卜青椒切丝。\n2. 调鱼香汁：生抽、香醋、白糖、淀粉加半碗水。\n3. 热油滑炒肉丝至变色盛出。\n4. 泡椒姜蒜末炒香，下三丝翻炒 2 分钟。\n5. 回锅肉丝，倒鱼香汁大火收浓出锅。',
        'image_url': 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'twice-cooked-pork',
        'name': '回锅肉',
        'category': '川菜',
        'description': '煮过再回锅炒，越炒越香。有些味道需要时间沉淀，有些人需要慢慢靠近，比如你，比如我。',
        'ingredients': '带皮五花肉 400 克\n蒜苗 4 根\n豆瓣酱 2 勺\n甜面酱 1 勺\n豆豉 1 小勺\n姜片 3 片\n花椒 少许\n白糖 少许',
        'steps': '1. 五花肉冷水下锅，加姜片花椒煮 20 分钟至筷子能插透。\n2. 捞出放凉切薄片，蒜苗斜切段。\n3. 热锅少油下肉片煸炒至微卷出油。\n4. 拨到一边，下豆瓣酱甜面酱豆豉炒出红油，与肉片炒匀。\n5. 加蒜苗段和少许糖，大火翻炒断生出锅。',
        'image_url': 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'boiled-fish',
        'name': '水煮鱼',
        'category': '川菜',
        'description': '一盆红油里藏着嫩滑的鱼片，看起来热烈，尝起来温柔。希望你尝到的时候，能想到热烈又温柔的我。',
        'ingredients': '草鱼 1 条\n黄豆芽 200 克\n郫县豆瓣酱 3 勺\n干辣椒 15 个\n花椒 1 把\n蛋清 1 个\n淀粉 2 勺\n姜蒜 适量\n盐 料酒 适量',
        'steps': '1. 草鱼片成鱼片，加盐、料酒、蛋清和淀粉抓匀腌 20 分钟。\n2. 豆芽焯水垫在盆底。\n3. 热油炒香豆瓣酱和姜蒜，加开水烧开。\n4. 先下鱼骨煮 5 分钟捞出，再下鱼片滑至变色连汤倒入盆中。\n5. 铺干辣椒花椒，淋一勺滚油激香。',
        'image_url': 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'pickled-cabbage-fish',
        'name': '酸菜鱼',
        'category': '川菜',
        'description': '酸辣开胃的汤底，鱼片嫩滑如云朵。心情不好的时候就该来一锅，酸味冲走烦恼，辣味唤醒快乐。',
        'ingredients': '黑鱼 1 条\n酸菜 300 克\n泡椒 5 个\n姜蒜 适量\n蛋清 1 个\n淀粉 2 勺\n白胡椒粉 少许\n干辣椒花椒 少许',
        'steps': '1. 黑鱼片成鱼片，用蛋清、淀粉和盐抓匀腌 20 分钟。\n2. 酸菜切段炒干水分，加姜蒜泡椒炒香。\n3. 加开水煮开，下鱼骨炖 8 分钟成奶白汤底。\n4. 下鱼片滑至变白，撒白胡椒粉出锅。\n5. 干辣椒花椒热油浇面。',
        'image_url': 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'yellow-braised-chicken',
        'name': '黄焖鸡',
        'category': '鲁菜',
        'description': '一锅黄焖鸡，有肉有菇有青椒，酱香浓郁。简单又丰盛，是那种不需要理由就想一起吃的饭。',
        'ingredients': '鸡腿 3 个\n干香菇 6 朵\n土豆 1 个\n青椒 2 个\n黄豆酱 1 勺\n生抽 2 勺\n老抽 1 勺\n姜片 4 片\n干辣椒 4 个\n冰糖 少许',
        'steps': '1. 鸡腿剁块焯水，香菇泡发对半切，土豆青椒切块。\n2. 热油炒冰糖至微黄，下鸡块翻炒上色。\n3. 加姜片、干辣椒、黄豆酱、生抽、老抽炒香。\n4. 加泡香菇的水没过鸡块，下香菇土豆焖 20 分钟。\n5. 收汁前加青椒块，翻匀焖 2 分钟出锅。',
        'image_url': 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'spicy-chicken',
        'name': '辣子鸡',
        'category': '川菜',
        'description': '辣椒堆里找鸡丁，是这道菜的仪式感。像极了我的心意——藏在很多日常里，但你一找就能找到。',
        'ingredients': '鸡腿肉 400 克\n干辣椒 30 个\n花椒 1 把\n姜蒜 适量\n生抽 2 勺\n料酒 1 勺\n白糖 半勺\n熟芝麻 1 勺',
        'steps': '1. 鸡腿肉切小丁，加生抽料酒腌 20 分钟。\n2. 油温六成热下鸡丁炸至金黄酥脆捞出。\n3. 升高油温复炸 30 秒逼出多余油脂。\n4. 留底油炒香干辣椒、花椒和姜蒜。\n5. 倒入鸡丁，加白糖翻炒，撒芝麻出锅。',
        'image_url': 'https://images.unsplash.com/photo-1562967914-608f82629710?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'crayfish',
        'name': '麻辣小龙虾',
        'category': '夜市',
        'description': '夏夜的正确打开方式：一盆小龙虾，两杯冰饮，和你聊到月亮下班。剥虾的手，今天想为你服务。',
        'ingredients': '小龙虾 1 千克\n啤酒 1 罐\n豆瓣酱 3 勺\n干辣椒 15 个\n花椒 1 把\n姜蒜 适量\n十三香 1 小勺\n白糖 1 勺\n葱段 适量',
        'steps': '1. 小龙虾刷洗干净，剪去虾须虾线。\n2. 热油爆香姜蒜、干辣椒、花椒和豆瓣酱。\n3. 倒入小龙虾翻炒至变红。\n4. 加啤酒、十三香和白糖，中火焖 15 分钟。\n5. 大火收汁，撒葱段出锅。',
        'image_url': 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'grilled-oysters',
        'name': '蒜蓉烤生蚝',
        'category': '烧烤',
        'description': '生蚝在炭火上滋滋作响，蒜蓉的香气飘满整条街。夜市烟火气里，想和你分享最肥美的那只。',
        'ingredients': '生蚝 6 只\n大蒜 1 头\n小米辣 2 个\n生抽 2 勺\n蚝油 1 勺\n食用油 3 勺\n葱花 适量',
        'steps': '1. 大蒜切末，热油炸至金黄，加小米辣、生抽、蚝油调成蒜蓉酱。\n2. 生蚝开壳洗净，保留蚝肉一侧。\n3. 每只铺满蒜蓉酱。\n4. 烤箱 200 度烤 8 分钟，或炭火烤至汁水沸腾。\n5. 撒葱花趁热吃。',
        'image_url': 'https://images.unsplash.com/photo-1540914124281-342587941389?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'lamb-skewers',
        'name': '孜然羊肉串',
        'category': '烧烤',
        'description': '炭火、孜然、辣椒面，还有晚风。撸串这件事，一个人是宵夜，两个人是故事。',
        'ingredients': '羊腿肉 400 克\n孜然粉 2 勺\n辣椒面 1 勺\n洋葱 半个\n生抽 1 勺\n盐 适量\n竹签 若干',
        'steps': '1. 羊肉切块，加洋葱丝、生抽和盐腌 30 分钟。\n2. 肥瘦相间串在竹签上。\n3. 炭火或烤箱烤至滋滋冒油。\n4. 撒孜然粉、辣椒面和盐。\n5. 再烤 1 分钟让香料入味。',
        'image_url': 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'peking-duck',
        'name': '北京烤鸭',
        'category': '京菜',
        'description': '金黄酥脆的鸭皮蘸白糖，是烤鸭最惊艳的一口。想带你去吃片鸭师傅片鸭的仪式感，再看你眼睛亮起来。',
        'ingredients': '烤鸭 1 只\n荷叶饼 20 张\n甜面酱 3 勺\n黄瓜 1 根\n大葱 2 根\n白糖 1 小碟',
        'steps': '1. 烤鸭趁热片成薄片，皮肉分离。\n2. 鸭皮蘸白糖，入口即化。\n3. 荷叶饼蒸热，抹甜面酱。\n4. 卷入鸭肉、黄瓜条和葱丝。\n5. 卷成筒状，一口一个满足。',
        'image_url': 'https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'xiaolongbao',
        'name': '小笼包',
        'category': '江浙菜',
        'description': '轻轻提，慢慢移，先开窗，后喝汤。吃小笼包是门学问，教你的那个人，得是愿意陪你慢慢学的人。',
        'ingredients': '中筋面粉 300 克\n猪肉末 250 克\n皮冻 150 克\n姜末 1 勺\n生抽 2 勺\n白糖 1 勺\n香油 1 勺\n白胡椒粉 少许',
        'steps': '1. 面粉加温水揉成光滑面团，醒 30 分钟。\n2. 肉末加姜末、生抽、糖、香油、白胡椒搅打上劲。\n3. 皮冻切碎拌入肉馅，冷藏 30 分钟。\n4. 面团搓条下剂，擀成中间厚边缘薄的皮，包入馅料捏出褶子。\n5. 水开上笼，旺火蒸 6 分钟，趁热蘸醋吃。',
        'image_url': 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'shengjianbao',
        'name': '生煎包',
        'category': '江浙菜',
        'description': '底脆、汤鲜、肉香，一口一个满足。上海早晨的街头，总有一锅生煎在等你，就像我在等你。',
        'ingredients': '中筋面粉 400 克\n酵母 4 克\n猪肉末 300 克\n皮冻 100 克\n姜末 葱花 适量\n生抽 2 勺\n芝麻 少许',
        'steps': '1. 面粉加酵母温水揉成面团，发酵至两倍大。\n2. 肉末加姜末、生抽、皮冻碎调成馅。\n3. 面团分成小剂子，包成小包子，收口朝下。\n4. 平底锅刷油，摆入包子小火煎至底部金黄。\n5. 加半碗水盖盖焖 8 分钟，开盖撒芝麻葱花，再煎 1 分钟。',
        'image_url': 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'scallion-noodles',
        'name': '葱油拌面',
        'category': '江浙菜',
        'description': '一把葱、一勺酱油、一碗面，简单到极致反而最难忘。想让你知道，复杂的世界里，我的喜欢就这么简单直接。',
        'ingredients': '细面 200 克\n小葱 8 根\n生抽 3 勺\n老抽 1 勺\n白糖 1 勺\n食用油 4 勺',
        'steps': '1. 小葱切长段，冷油下锅，小火慢熬至焦黄捞出。\n2. 生抽、老抽、白糖入葱油，小火煮至冒泡成葱油酱。\n3. 面条煮至断生捞出，沥干水分。\n4. 趁热浇上葱油酱拌匀。\n5. 摆上炸酥的葱段即可。',
        'image_url': 'https://images.unsplash.com/photo-1552611052-33e04de081de?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'guotie',
        'name': '锅贴',
        'category': '北方菜',
        'description': '金黄酥脆的冰花底，咬下去汁水四溢。冬天就该配一碟热锅贴，暖手，也暖心。',
        'ingredients': '饺子皮 30 张\n猪肉末 300 克\n白菜 200 克\n姜末 1 勺\n生抽 2 勺\n香油 1 勺\n面粉 1 小勺（调冰花水）',
        'steps': '1. 白菜切碎加盐杀水挤干，与肉末、姜末、生抽、香油拌成馅。\n2. 饺子皮包入馅料，捏成两边开口的锅贴。\n3. 平底锅刷油，摆入锅贴小火煎至底部微黄。\n4. 面粉加水调成稀面糊水，倒入锅中没过锅贴底部。\n5. 盖盖焖 8 分钟，开盖大火收干，倒扣出冰花锅贴。',
        'image_url': 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'luosifen',
        'name': '螺蛳粉',
        'category': '广西菜',
        'description': '闻着劝退，吃着真香，是螺蛳粉的倔强。很多美好都是这样，要放下成见才会遇见，比如你。',
        'ingredients': '干米粉 200 克\n螺蛳汤料包 1 包\n酸笋 80 克\n腐竹 50 克\n花生米 30 克\n木耳 榨菜 适量\n辣油 香醋 按口味',
        'steps': '1. 干米粉冷水浸泡 2 小时或直接煮 10 分钟至筷子能夹断。\n2. 捞出米粉装碗，摆上酸笋、腐竹、花生、木耳、榨菜。\n3. 汤料包加水煮开，浇入碗中。\n4. 按口味淋辣油和香醋。\n5. 拌匀开吃，记得先喝一口汤。',
        'image_url': 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'cheongfun',
        'name': '肠粉',
        'category': '粤菜',
        'description': '米浆蒸成薄如蝉翼的粉皮，裹着鲜虾和鸡蛋，淋上豉油。广东人的早晨，从一碟肠粉开始，温柔又踏实。',
        'ingredients': '粘米粉 150 克\n澄粉 30 克\n虾仁 100 克\n鸡蛋 2 个\n生菜 2 片\n蒸鱼豉油 3 勺\n葱花 适量',
        'steps': '1. 粘米粉、澄粉加 350 毫升水调成米浆。\n2. 蒸盘刷油，舀入一层薄米浆，铺虾仁和鸡蛋液。\n3. 大火蒸 2 分钟至粉皮鼓泡变透明。\n4. 用刮板卷起粉皮装盘，铺上焯水的生菜。\n5. 淋蒸鱼豉油，撒葱花。',
        'image_url': 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'har-gow',
        'name': '虾饺',
        'category': '粤菜',
        'description': '晶莹剔透的皮子里，藏着一整只弹牙的虾。早茶的意义不只是吃，是愿意陪你慢慢坐一个上午。',
        'ingredients': '澄面 150 克\n木薯淀粉 50 克\n鲜虾仁 300 克\n肥膘肉 30 克\n笋丁 50 克\n盐 白胡椒粉 适量\n猪油 1 勺',
        'steps': '1. 虾仁一半拍成泥，一半切丁，与肥膘肉末、笋丁、调料搅打成馅。\n2. 澄面加木薯淀粉，用沸水烫面揉成团，加猪油揉匀。\n3. 面团搓条下剂，用刀面压成薄圆皮。\n4. 包入馅料，捏出月牙形褶子。\n5. 水开大火蒸 5 分钟，皮变透明即可。',
        'image_url': 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'congee',
        'name': '艇仔粥',
        'category': '粤菜',
        'description': '一碗粥里有鱼片、鱿鱼、花生、油条，广东人把整个世界煮进了粥里。我的关心也想这样，细水长流地煮进每一天。',
        'ingredients': '大米 150 克\n鱼片 80 克\n鱿鱼 50 克\n虾仁 50 克\n炸花生米 30 克\n油条 1 根\n姜丝 葱花 适量\n盐 白胡椒粉 少许',
        'steps': '1. 大米加少许油盐腌 20 分钟，加 8 倍水煮开。\n2. 转小火熬 40 分钟至米粒开花、粥底绵滑。\n3. 鱼片、鱿鱼、虾仁加姜丝烫入粥中，煮 1 分钟。\n4. 加盐和白胡椒粉调味。\n5. 撒炸花生、油条碎和葱花。',
        'image_url': 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'claypot-rice',
        'name': '煲仔饭',
        'category': '粤菜',
        'description': '锅巴是煲仔饭的灵魂，咔嚓一口，香气在嘴里炸开。腊味、米饭、锅巴，简单组合却叫人惦记，就像好日子不必复杂。',
        'ingredients': '丝苗米 200 克\n腊肠 2 根\n腊肉 80 克\n青菜 2 棵\n鸡蛋 1 个\n生抽 2 勺\n蚝油 1 勺\n白糖 少许\n香油 少许',
        'steps': '1. 丝苗米淘洗后浸泡 30 分钟，加水入砂锅，水没过米面半指。\n2. 大火烧开转小火，煮至水收干、米饭冒小孔。\n3. 铺腊肠片和腊肉片，盖盖小火焗 10 分钟。\n4. 沿锅边淋一圈油，打一个鸡蛋，摆上焯水的青菜。\n5. 再焗 5 分钟出锅巴，淋生抽蚝油糖调成的豉油。',
        'image_url': 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'mango-pomelo-sago',
        'name': '杨枝甘露',
        'category': '甜品',
        'description': '芒果的甜、西柚的酸、西米的弹，一口就治愈。甜品是生活给的小奖励，而你是生活给我的大奖。',
        'ingredients': '芒果 2 个\n西柚 半个\n西米 50 克\n椰浆 200 毫升\n牛奶 100 毫升\n白糖 20 克',
        'steps': '1. 水开后下西米，煮 15 分钟至剩小白点，关火焖 10 分钟至全透明。\n2. 西米过冷水沥干，加糖拌匀。\n3. 一个芒果切丁，一个芒果加椰浆、牛奶打成芒果浆。\n4. 西柚剥出果肉粒。\n5. 碗中放西米，倒芒果浆，铺芒果丁和西柚粒，冷藏后更佳。',
        'image_url': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'double-skin-milk',
        'name': '双皮奶',
        'category': '甜品',
        'description': '奶皮是双皮奶的勋章，一勺下去，嫩滑得像初恋。广东的糖水铺子里，藏着最朴素的甜。',
        'ingredients': '全脂牛奶 400 毫升\n蛋清 2 个\n白糖 30 克',
        'steps': '1. 牛奶小火加热至微沸，倒入碗中静置结出第一层奶皮。\n2. 用筷子挑起奶皮一角，把奶液缓缓倒出，奶皮留在碗底。\n3. 奶液加蛋清和糖搅匀，过筛两遍去泡。\n4. 沿碗边把奶液倒回碗中，让奶皮浮起。\n5. 盖保鲜膜，水开后中小火蒸 12 分钟，焖 5 分钟。',
        'image_url': 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'mango-pancake',
        'name': '芒果班戟',
        'category': '甜品',
        'description': '软糯的饼皮裹着奶油和大块芒果，一口咬下去全是满足。港式甜品店的招牌，也是我想给你的甜蜜。',
        'ingredients': '低筋面粉 80 克\n鸡蛋 2 个\n牛奶 200 毫升\n黄油 15 克\n淡奶油 200 毫升\n白糖 40 克\n芒果 1 个',
        'steps': '1. 鸡蛋加糖打散，加牛奶和融化的黄油拌匀。\n2. 筛入低筋面粉搅成细腻面糊，过筛后静置 30 分钟。\n3. 平底锅小火摊成薄饼皮，放凉备用。\n4. 淡奶油加糖打发至硬性，芒果切大条。\n5. 饼皮上铺奶油和芒果条，折成方形包好，冷藏 30 分钟定型。',
        'image_url': 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'tiramisu',
        'name': '提拉米苏',
        'category': '甜品',
        'description': '提拉米苏在意大利语里是「带我走」。所以今天想送你的不是蛋糕，是一句很认真的邀请。',
        'ingredients': '马斯卡彭奶酪 250 克\n手指饼干 12 根\n蛋黄 2 个\n白糖 40 克\n浓缩咖啡 100 毫升\n淡奶油 150 毫升\n可可粉 适量',
        'steps': '1. 蛋黄加糖隔热水打发至浓稠发白，晾凉。\n2. 马斯卡彭奶酪打至顺滑，与蛋黄糊拌匀。\n3. 淡奶油打发至有纹路，分次拌入奶酪糊。\n4. 手指饼干快速蘸一下浓缩咖啡，铺在模具底。\n5. 铺一层奶酪糊，重复一层饼干一层糊，冷藏 4 小时以上，吃前筛可可粉。',
        'image_url': 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'souffle',
        'name': '舒芙蕾',
        'category': '甜品',
        'description': '蓬松轻盈，出炉十分钟就开始塌陷，所以要趁热吃。它教会我：有些美好不能等，比如约你。',
        'ingredients': '鸡蛋 3 个\n低筋面粉 30 克\n牛奶 150 毫升\n白糖 40 克\n黄油 20 克\n糖粉 少许',
        'steps': '1. 蛋黄加牛奶、融化的黄油和过筛的面粉搅成糊。\n2. 蛋白分三次加糖，打发至提起有小弯钩。\n3. 蛋白霜分次翻拌进蛋黄糊，动作轻快防消泡。\n4. 烤盅内壁刷黄油撒糖，倒入面糊抹平。\n5. 烤箱 180 度烤 18 分钟，出炉撒糖粉立即吃。',
        'image_url': 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'matcha-crepe',
        'name': '抹茶千层',
        'category': '甜品',
        'description': '一层一层叠加的薄饼，抹茶的微苦平衡奶油的甜。人生也是层层叠叠的，希望每层都有你。',
        'ingredients': '低筋面粉 100 克\n鸡蛋 3 个\n牛奶 300 毫升\n抹茶粉 8 克\n白糖 50 克\n黄油 20 克\n淡奶油 300 毫升',
        'steps': '1. 抹茶粉加少许牛奶调开，与鸡蛋、牛奶、融化的黄油搅匀。\n2. 筛入低筋面粉和糖，拌成细腻面糊过筛。\n3. 平底锅小火摊成约 20 张薄饼皮，放凉。\n4. 淡奶油加糖打发，加少许抹茶粉拌成抹茶奶油。\n5. 一层饼皮一层奶油叠好，冷藏 2 小时定型后切块。',
        'image_url': 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'milk-tea',
        'name': '珍珠奶茶',
        'category': '饮品',
        'description': '奶茶三分糖，珍珠加双份。甜的刚刚好，嚼的刚刚好，像我们聊天的节奏。下次见面，请你喝第一杯。',
        'ingredients': '红茶 2 包\n牛奶 300 毫升\n珍珠粉圆 100 克\n黑糖 50 克\n白糖 适量\n冰块 适量',
        'steps': '1. 珍珠粉圆入沸水煮 20 分钟，关火焖 15 分钟至透明。\n2. 捞出珍珠，用黑糖水煮至挂浆入味。\n3. 红茶包加热水泡 5 分钟，加牛奶和糖调成奶茶。\n4. 杯底铺黑糖珍珠，杯壁淋黑糖浆挂壁。\n5. 加冰块，倒入奶茶，搅匀开喝。',
        'image_url': 'https://images.unsplash.com/photo-1558857563-b371033873b8?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'takoyaki',
        'name': '章鱼小丸子',
        'category': '小吃',
        'description': '外脆内软，章鱼块弹牙，木鱼花在热气里跳舞。街头小吃的快乐，简单又真实，像我们日常的聊天。',
        'ingredients': '低筋面粉 150 克\n鸡蛋 2 个\n水 300 毫升\n章鱼粒 150 克\n包菜丝 适量\n照烧酱 2 勺\n沙拉酱 2 勺\n木鱼花 海苔碎 适量',
        'steps': '1. 低筋面粉、鸡蛋、水搅成稀面糊。\n2. 丸子模具刷油烧热，倒入八分满面糊。\n3. 每个孔放章鱼粒和包菜丝，再补满面糊。\n4. 底部定型后用签子翻动，滚成圆球。\n5. 煎至金黄出锅，挤照烧酱沙拉酱，撒木鱼花和海苔碎。',
        'image_url': 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'sushi',
        'name': '寿司',
        'category': '日料',
        'description': '新鲜的鱼生和微酸的醋饭，是日料店师傅的手艺，也是想请你慢慢品尝的仪式感。',
        'ingredients': '寿司米 300 克\n寿司醋 3 勺\n三文鱼 150 克\n海苔 2 张\n黄瓜 半根\n山葵 酱油 适量',
        'steps': '1. 寿司米煮好后趁热拌入寿司醋，扇凉至室温。\n2. 手上蘸水防粘，把醋饭握成小团。\n3. 三文鱼切薄片盖在饭团上轻压成型。\n4. 黄瓜切条，配海苔做细卷。\n5. 摆盘配山葵和酱油，一口一个。',
        'image_url': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'ramen',
        'name': '豚骨拉面',
        'category': '日料',
        'description': '汤头熬了一整天，面条吸满浓汤。深夜的一碗拉面，是独自在外的人最想要的那口温暖，以后有我陪你吃。',
        'ingredients': '拉面 2 人份\n猪骨 1 千克\n叉烧肉 6 片\n溏心蛋 2 个\n海苔 2 片\n葱花 木耳丝 适量\n酱油 味噌 适量',
        'steps': '1. 猪骨焯水后加足量水，大火熬 6 小时至汤色奶白。\n2. 汤底加酱油或味噌调味。\n3. 拉面煮熟沥干，装入碗中。\n4. 浇入滚烫的豚骨汤。\n5. 摆上叉烧、对半切的溏心蛋、海苔、木耳丝和葱花。',
        'image_url': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'spaghetti',
        'name': '番茄肉酱意面',
        'category': '西餐',
        'description': '番茄肉酱熬得浓稠，面条卷成一口的优雅。西餐的仪式感配中餐的烟火气，像我们慢慢了解彼此的过程。',
        'ingredients': '意面 200 克\n牛肉末 200 克\n番茄 3 个\n洋葱 半个\n蒜末 2 瓣\n番茄酱 3 勺\n黑胡椒 盐 适量\n橄榄油 2 勺',
        'steps': '1. 意面加盐煮 10 分钟，捞出拌少许橄榄油。\n2. 番茄去皮切丁，洋葱切末。\n3. 热油炒香洋葱蒜末，下牛肉末炒散变色。\n4. 加番茄丁和番茄酱，小火熬 15 分钟成浓稠肉酱。\n5. 加盐黑胡椒调味，拌入意面，撒芝士粉。',
        'image_url': 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'pizza',
        'name': '玛格丽特披萨',
        'category': '西餐',
        'description': '番茄、马苏里拉、罗勒，红白绿像意大利的国旗。经典的永远经典，就像有些喜欢，第一眼就知道。',
        'ingredients': '高筋面粉 250 克\n酵母 3 克\n番茄酱 4 勺\n马苏里拉芝士 200 克\n番茄 1 个\n新鲜罗勒叶 8 片\n橄榄油 2 勺\n盐 少许',
        'steps': '1. 面粉加酵母、盐、水和橄榄油揉成面团，发酵 1 小时。\n2. 面团擀成圆饼，边缘稍厚。\n3. 饼底抹番茄酱，铺番茄片和撕碎的马苏里拉。\n4. 烤箱 250 度预热，烤 8 分钟至芝士融化、边缘焦黄。\n5. 出炉撒罗勒叶，淋橄榄油。',
        'image_url': 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'steak',
        'name': '香煎牛排',
        'category': '西餐',
        'description': '五分熟的牛排，切开是漂亮的粉红色。想带你去一家安静的店，听牛排滋滋响，看烛光在你眼里闪。',
        'ingredients': '西冷牛排 1 块（250 克）\n黄油 20 克\n大蒜 3 瓣\n迷迭香 1 枝\n黑胡椒 盐 适量\n橄榄油 1 勺',
        'steps': '1. 牛排室温回温 30 分钟，用厨房纸吸干表面水分。\n2. 两面撒盐和黑胡椒抹匀。\n3. 铸铁锅大火烧至冒烟，加橄榄油，下牛排煎 90 秒。\n4. 翻面再煎 90 秒，加黄油、拍扁的大蒜和迷迭香。\n5. 用勺子把黄油反复淋在牛排上 1 分钟，出锅静置 5 分钟再切。',
        'image_url': 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'burger',
        'name': '芝士牛肉汉堡',
        'category': '西餐',
        'description': '牛肉饼厚实多汁，芝士融化拉丝。汉堡的美味不需要解释，就像我想见你也不需要理由。',
        'ingredients': '汉堡胚 2 个\n牛肉末 300 克\n切达芝士 2 片\n生菜 2 片\n番茄 1 个\n洋葱 半个\n蛋黄酱 番茄酱 适量\n盐 黑胡椒 适量',
        'steps': '1. 牛肉末加盐黑胡椒，压成 2 厘米厚肉饼。\n2. 平底锅烧热，肉饼两面各煎 2 分钟。\n3. 翻面后盖上芝士片，盖上锅盖焖 30 秒至融化。\n4. 汉堡胚切开烤热，抹蛋黄酱和番茄酱。\n5. 依次放生菜、番茄、洋葱圈、芝士肉饼，合上开吃。',
        'image_url': 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'mushroom-soup',
        'name': '奶油蘑菇汤',
        'category': '西餐',
        'description': '香浓顺滑的奶油蘑菇汤，配一块烤脆的法棍。雨天喝一碗，整个人都暖起来，希望我也是你的那碗热汤。',
        'ingredients': '白蘑菇 300 克\n洋葱 半个\n黄油 20 克\n淡奶油 150 毫升\n牛奶 200 毫升\n面粉 1 勺\n盐 黑胡椒 适量',
        'steps': '1. 蘑菇切片，洋葱切丁。\n2. 黄油融化，炒香洋葱至透明，下蘑菇炒至出水变软。\n3. 加面粉炒匀，倒入牛奶小火煮 5 分钟。\n4. 用料理机打成细腻的浓汤，倒回锅中。\n5. 加淡奶油、盐和黑胡椒调味，煮至微沸，配烤面包丁吃。',
        'image_url': 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'chopped-pepper-fish-head',
        'name': '剁椒鱼头',
        'category': '湘菜',
        'description': '铺满剁椒的鱼头蒸得鲜红油亮，辣得满头大汗也停不下筷子。湖南人把热情都埋进菜里，而我想把对你的喜欢摊开给你看。',
        'ingredients': '胖头鱼鱼头 1 个（约 1 千克）\n剁椒 150 克\n小米辣 3 个\n姜 1 块\n蒜 5 瓣\n蒸鱼豉油 3 勺\n料酒 2 勺\n食用油 3 勺\n葱花 适量',
        'steps': '1. 鱼头对半剖开，去鳃洗净，抹料酒和盐腌 15 分钟。\n2. 姜蒜切末，与剁椒、小米辣拌匀，铺满鱼头。\n3. 水开后上锅，大火蒸 12 分钟。\n4. 出锅倒掉多余汤汁，淋蒸鱼豉油。\n5. 撒葱花，浇一勺滚油激香。',
        'image_url': 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'pepper-fried-pork',
        'name': '辣椒炒肉',
        'category': '湘菜',
        'description': '湖南人餐桌上最下饭的一道菜，螺丝椒的香辣钻进肉片里。平凡的日子配这一盘，能多吃两碗饭，就像有你在，日常也闪闪发光。',
        'ingredients': '五花肉 200 克\n螺丝椒 6 个\n蒜 4 瓣\n豆豉 1 小勺\n生抽 2 勺\n老抽 半勺\n盐 少许',
        'steps': '1. 五花肉切薄片，螺丝椒斜切段。\n2. 干锅煸炒辣椒，加少许盐煸出虎皮盛出。\n3. 热锅下肉片，煸炒至出油微卷。\n4. 加蒜片和豆豉炒香，加生抽老抽调味。\n5. 倒回辣椒大火翻匀出锅。',
        'image_url': 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'braised-prawns',
        'name': '油焖大虾',
        'category': '鲁菜',
        'description': '红亮的大虾在油里焖出鲜甜，虾头里的膏是藏起来的惊喜。鲁菜讲火候，我讲心动——每一只虾壳都想替你剥。',
        'ingredients': '大虾 500 克\n姜 4 片\n蒜 3 瓣\n生抽 2 勺\n白糖 1 勺\n料酒 1 勺\n番茄酱 1 勺\n小葱 2 根',
        'steps': '1. 大虾剪去虾须虾枪，开背去虾线。\n2. 热油下大虾，中火煎至两面变红出虾油。\n3. 加姜蒜末炒香，烹入料酒。\n4. 加生抽、白糖、番茄酱和半碗水。\n5. 加盖焖 3 分钟，大火收汁撒葱花。',
        'image_url': 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'stinky-mandarin-fish',
        'name': '臭鳜鱼',
        'category': '徽菜',
        'description': '闻着臭吃着香，鳜鱼肉像蒜瓣一样白嫩。徽菜的头牌，和很多心动一样——一开始不习惯，尝过就忘不掉。',
        'ingredients': '臭鳜鱼 1 条\n五花肉丁 50 克\n笋丁 50 克\n姜蒜末 适量\n豆瓣酱 2 勺\n生抽 1 勺\n糖 1 勺\n料酒 2 勺',
        'steps': '1. 臭鳜鱼洗净打花刀，擦干水分。\n2. 热油下鱼，两面煎至微黄盛出。\n3. 底油炒香五花肉丁、姜蒜末和笋丁。\n4. 加豆瓣酱、生抽、糖和料酒，加半碗水烧开。\n5. 回锅鱼，中火烧 8 分钟，收汁装盘。',
        'image_url': 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'lychee-pork',
        'name': '荔枝肉',
        'category': '闽菜',
        'description': '形似荔枝、酸甜开胃，是福州人从小吃到大的味道。红曲染色的肉球咬开是荸荠的脆，像惊喜藏在平凡里。',
        'ingredients': '猪梅花肉 300 克\n荸荠 6 个\n红曲粉 1 小勺\n番茄酱 3 勺\n香醋 2 勺\n白糖 2 勺\n淀粉 适量\n蒜末 少许',
        'steps': '1. 肉切十字花刀，再切小块，加盐和红曲粉腌 20 分钟。\n2. 每块包入荸荠粒，裹淀粉捏成球。\n3. 油温六成热下肉球，炸至表面微酥捞出。\n4. 调汁：番茄酱、香醋、白糖、蒜末加少许水。\n5. 倒汁烧浓，下肉球翻炒裹匀。',
        'image_url': 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'satay-noodles',
        'name': '沙茶面',
        'category': '闽菜',
        'description': '沙茶酱熬出的浓汤，鲜甜里带着花生香，是厦门海风的味道。加满喜欢的料，一碗下肚，胃和心都满了。',
        'ingredients': '碱水面 200 克\n沙茶酱 3 勺\n花生酱 1 勺\n虾 6 只\n鱿鱼 100 克\n豆芽 青菜 适量\n蒜末 1 勺\n高汤 500 毫升',
        'steps': '1. 高汤烧开，加沙茶酱和花生酱搅化，小火熬成沙茶汤底。\n2. 碱水面煮熟捞出装碗。\n3. 虾、鱿鱼、豆芽和青菜依次烫熟，码在面上。\n4. 浇入滚烫的沙茶汤。\n5. 撒蒜末，趁热拌匀开吃。',
        'image_url': 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'west-lake-vinegar-fish',
        'name': '西湖醋鱼',
        'category': '江浙菜',
        'description': '草鱼水煮后浇上琥珀色的糖醋汁，嫩滑里带着湖水的灵气。杭州人的讲究都在这条鱼里，酸酸甜甜像初恋。',
        'ingredients': '草鱼 1 条（约 700 克）\n姜 1 块\n香醋 4 勺\n白糖 3 勺\n生抽 2 勺\n料酒 2 勺\n淀粉 1 勺\n小葱 适量',
        'steps': '1. 草鱼去鳞去腮，两面各切几刀。\n2. 锅中加水、姜片和料酒烧开，鱼入锅煮 5 分钟至断生。\n3. 捞出装盘，煮鱼的水留一碗。\n4. 用鱼汤加香醋、白糖、生抽烧开，淀粉勾芡。\n5. 糖醋汁浇在鱼上，撒姜丝葱花。',
        'image_url': 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'longjing-shrimp',
        'name': '龙井虾仁',
        'category': '江浙菜',
        'description': '虾仁玉白、茶叶碧绿，一道菜里藏着整个江南的春天。清淡里见功夫，就像喜欢一个人，越是平淡越见真心。',
        'ingredients': '河虾仁 300 克\n龙井茶叶 3 克\n蛋清 1 个\n淀粉 1 勺\n料酒 1 勺\n盐 适量',
        'steps': '1. 虾仁加盐、蛋清、淀粉抓匀腌 20 分钟。\n2. 龙井茶用 80 度热水泡开，留茶汤和茶叶。\n3. 热油滑炒虾仁至变色盛出。\n4. 倒茶汤和茶叶入锅，加盐调味。\n5. 回锅虾仁快速翻匀，淋少许水淀粉出锅。',
        'image_url': 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'guobaorou',
        'name': '锅包肉',
        'category': '东北菜',
        'description': '金黄的肉片裹着透亮的糖醋汁，咬下去咔嚓一声。东北人的豪爽里藏着这道酸甜，像粗中有细的温柔。',
        'ingredients': '猪里脊 300 克\n土豆淀粉 100 克\n白糖 3 勺\n白醋 3 勺\n番茄酱 1 勺\n姜丝 胡萝卜丝 适量\n香菜 少许',
        'steps': '1. 里脊切厚片，用刀背轻拍松，加盐腌 10 分钟。\n2. 土豆淀粉加水调成挂糊，裹匀肉片。\n3. 油温七成热下肉片炸至定型捞出，复炸至金黄酥脆。\n4. 调汁：白糖、白醋、番茄酱加少许水。\n5. 汁烧浓下肉片、姜丝胡萝卜丝快速翻匀，撒香菜。',
        'image_url': 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'disanxian',
        'name': '地三鲜',
        'category': '东北菜',
        'description': '茄子土豆青椒，三种最朴素的蔬菜炒出最下饭的一盘。东北菜的实在，就是菜不多说漂亮话，但管饱管香。',
        'ingredients': '茄子 1 个\n土豆 2 个\n青椒 2 个\n蒜 4 瓣\n生抽 2 勺\n蚝油 1 勺\n白糖 半勺\n淀粉 1 勺',
        'steps': '1. 茄子土豆切滚刀块，青椒掰块，土豆炸至金黄。\n2. 茄子裹少许淀粉，炸至表面微皱捞出。\n3. 调碗汁：生抽、蚝油、白糖、淀粉加半碗水。\n4. 爆香蒜末，下青椒翻炒几下。\n5. 倒回茄子土豆，淋碗汁大火收浓。',
        'image_url': 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'chicken-mushroom-stew',
        'name': '小鸡炖蘑菇',
        'category': '东北菜',
        'description': '榛蘑的香气钻进鸡肉里，粉条吸饱汤汁，是东北人待客的最高礼仪。一锅炖菜，热乎乎地暖到心里。',
        'ingredients': '土鸡 半只\n干榛蘑 80 克\n红薯粉条 100 克\n姜 4 片\n八角 2 颗\n生抽 2 勺\n老抽 1 勺\n盐 适量',
        'steps': '1. 榛蘑泡发洗净，泡蘑菇水留用。\n2. 鸡块焯水，热油下姜片八角炒香，下鸡块炒至微黄。\n3. 加生抽老抽炒上色，倒泡蘑菇水没过鸡块。\n4. 下榛蘑，小火炖 40 分钟。\n5. 加泡软的粉条再炖 10 分钟，加盐调味。',
        'image_url': 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'dapanji',
        'name': '大盘鸡',
        'category': '西北菜',
        'description': '一整个大盘子端上来，鸡肉、土豆、皮带面浸在红亮的汤汁里。新疆人的热情，就是要让你吃撑了才肯放你走。',
        'ingredients': '三黄鸡 半只\n土豆 2 个\n青红椒 各 1 个\n干辣椒 8 个\n花椒 1 小把\n豆瓣酱 2 勺\n啤酒 1 罐\n姜蒜 适量\n皮带面 200 克',
        'steps': '1. 鸡块焯水，土豆切滚刀块。\n2. 热油炒糖色，下鸡块翻炒上色。\n3. 加姜蒜、干辣椒、花椒和豆瓣酱炒出红油。\n4. 倒啤酒没过鸡块，下土豆炖 20 分钟。\n5. 加青红椒收汁，盘底铺煮好的皮带面，连汁浇上。',
        'image_url': 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'lanzhou-noodles',
        'name': '兰州牛肉面',
        'category': '西北菜',
        'description': '一清二白三红四绿，牛肉面是兰州人的清晨闹钟。汤清面筋道，喝一口汤，一天都精神起来。',
        'ingredients': '拉面 200 克\n牛肉 300 克\n白萝卜 半根\n牛骨 500 克\n香菜 蒜苗 适量\n油泼辣子 2 勺\n盐 花椒 草果 适量',
        'steps': '1. 牛骨和牛肉冷水下锅，加花椒草果，小火炖 2 小时成清汤。\n2. 牛肉捞出切片，白萝卜切薄片入汤煮熟。\n3. 拉面煮熟捞入碗中。\n4. 浇入滚烫的牛肉汤，码上牛肉片和萝卜。\n5. 撒香菜蒜苗，淋油泼辣子。',
        'image_url': 'https://images.unsplash.com/photo-1552611052-33e04de081de?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'roujiamo',
        'name': '肉夹馍',
        'category': '西北菜',
        'description': '白吉馍烤得外酥里软，腊汁肉剁得肥瘦相间，馍里夹的是西安千年的烟火气。一口下去，全是满足。',
        'ingredients': '面粉 300 克\n酵母 3 克\n五花肉 500 克\n冰糖 20 克\n生抽 2 勺\n老抽 1 勺\n姜 4 片\n八角 香叶 桂皮 适量',
        'steps': '1. 面粉加酵母和面发酵，擀成小圆饼，平底锅烙至两面金黄。\n2. 五花肉切块焯水，加冰糖炒糖色。\n3. 加姜片、八角、香叶、桂皮、生抽老抽和热水。\n4. 小火卤 1 小时至肉烂，捞出剁碎加少许卤汁。\n5. 馍从中间剖开，夹入剁好的肉。',
        'image_url': 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'liangpi',
        'name': '凉皮',
        'category': '西北菜',
        'description': '透亮的凉皮拌上蒜水、油泼辣子和香醋，夏天没有它就少了一半快乐。酸辣爽滑，一口凉到心。',
        'ingredients': '面粉 300 克\n黄瓜 1 根\n豆芽 100 克\n大蒜 4 瓣\n油泼辣子 2 勺\n香醋 2 勺\n生抽 1 勺\n芝麻酱 1 勺',
        'steps': '1. 面粉加水揉成面团，洗出面筋，面浆静置 4 小时。\n2. 面筋蒸熟切块，面浆撇去上层清水搅匀。\n3. 平盘刷油，倒一层面浆，蒸 2 分钟成凉皮。\n4. 凉皮切条，与黄瓜丝、豆芽、面筋装碗。\n5. 加蒜水、油泼辣子、香醋、生抽和芝麻酱拌匀。',
        'image_url': 'https://images.unsplash.com/photo-1552611052-33e04de081de?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'crossing-bridge-noodles',
        'name': '过桥米线',
        'category': '云南菜',
        'description': '滚烫的鸡汤浮着一层油保温，食材一样样下去烫熟。云南人把耐心煮进这碗米线，就像好的感情，急不得。',
        'ingredients': '米线 200 克\n鸡腿 1 个\n火腿片 50 克\n鹌鹑蛋 2 个\n豆芽 豆腐皮 韭菜 适量\n鸡汤 800 毫升\n盐 白胡椒 适量',
        'steps': '1. 鸡汤熬好后保持滚烫，倒入大海碗。\n2. 依次下火腿片、鸡片、鹌鹑蛋烫熟。\n3. 再下豆芽、豆腐皮和韭菜。\n4. 最后下煮软的米线。\n5. 加盐和白胡椒粉，喝汤吃粉。',
        'image_url': 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'sour-soup-fish',
        'name': '凯里酸汤鱼',
        'category': '贵州菜',
        'description': '苗家酸汤用番茄和米汤自然发酵，酸得明亮开胃。一锅红汤煮活鱼，是贵州人『三天不吃酸，走路打蹿蹿』的执念。',
        'ingredients': '草鱼 1 条\n酸汤 600 毫升\n番茄 2 个\n木姜子 1 小勺\n姜蒜 适量\n豆芽 100 克\n盐 适量\n蘸水 按口味',
        'steps': '1. 草鱼切块，番茄切块。\n2. 酸汤倒入锅中烧开，加番茄和木姜子煮 5 分钟。\n3. 下鱼块煮 8 分钟至熟。\n4. 豆芽垫底，鱼和汤一起倒入。\n5. 配糊辣椒蘸水吃。',
        'image_url': 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'hot-dry-noodles',
        'name': '热干面',
        'category': '湖北菜',
        'description': '芝麻酱裹满碱水面，拌开的那一刻香气扑鼻。武汉人的早晨，从端着一碗热干面边走边吃开始。',
        'ingredients': '碱水面 200 克\n芝麻酱 2 勺\n香油 1 勺\n生抽 1 勺\n香醋 1 勺\n萝卜干 酸豆角 适量\n葱花 适量',
        'steps': '1. 芝麻酱用香油调稀至顺滑。\n2. 碱水面煮至八分熟捞出，淋香油抖散晾凉。\n3. 吃前回锅烫 10 秒捞出。\n4. 加芝麻酱、生抽、香醋拌匀。\n5. 撒萝卜干、酸豆角和葱花。',
        'image_url': 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'zhajiangmian',
        'name': '老北京炸酱面',
        'category': '京菜',
        'description': '干黄酱和甜面酱小火慢炸的肉酱，配齐七碟八碗的面码。北京人的讲究，都在这一碗面的仪式感里。',
        'ingredients': '手擀面 200 克\n五花肉丁 150 克\n干黄酱 2 勺\n甜面酱 1 勺\n黄瓜丝 萝卜丝 豆芽 各 1 碟\n葱姜末 适量',
        'steps': '1. 干黄酱加温水澥开，与甜面酱混合。\n2. 热油下五花肉丁，煸炒至微焦出油。\n3. 下葱姜末炒香，倒酱小火炸 10 分钟至油酱分离。\n4. 面条煮熟过一下温水，捞入碗中。\n5. 浇上炸酱，码上黄瓜丝、萝卜丝、豆芽拌匀。',
        'image_url': 'https://images.unsplash.com/photo-1552611052-33e04de081de?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'yanduxian',
        'name': '腌笃鲜',
        'category': '江浙菜',
        'description': '咸肉、鲜肉、春笋小火笃出一锅奶白汤，鲜掉眉毛。江南春天的第一口，就是把山里的笋和水里的肉炖在一起。',
        'ingredients': '咸肉 150 克\n五花肉 200 克\n春笋 2 根\n百叶结 6 个\n姜 3 片\n料酒 2 勺\n葱 1 根',
        'steps': '1. 咸肉和五花肉切块，冷水下锅焯水。\n2. 春笋切滚刀块，焯水去涩。\n3. 锅中加水，下两种肉、姜片和料酒。\n4. 大火烧开转小火笃 40 分钟。\n5. 加春笋和百叶结再笃 20 分钟，撒葱花。',
        'image_url': 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'white-cut-chicken',
        'name': '白切鸡',
        'category': '粤菜',
        'description': '三浸三提浸熟的鸡，皮黄肉白，鸡骨还带一点红。粤菜的最高境界是原味，蘸一点姜葱蓉，鲜到说不出话。',
        'ingredients': '三黄鸡 1 只\n姜 1 大块\n小葱 4 根\n盐 适量\n花生油 3 勺',
        'steps': '1. 锅中加水、姜片葱结烧开。\n2. 提着鸡头把鸡浸入沸水，提起倒出腹腔的水，反复三次。\n3. 整鸡入锅，小火浸煮 20 分钟。\n4. 捞出过冰水，晾凉斩件。\n5. 姜葱剁蓉，加盐淋热油成蘸料。',
        'image_url': 'https://images.unsplash.com/photo-1562967914-608f82629710?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'beef-chow-fun',
        'name': '干炒牛河',
        'category': '粤菜',
        'description': '河粉炒得油亮干香，牛肉滑嫩，锅气十足。大排档的深夜，一盘干炒牛河配冰可乐，就是最朴素的快乐。',
        'ingredients': '河粉 300 克\n牛里脊 150 克\n豆芽 100 克\n韭黄 50 克\n洋葱 半个\n生抽 2 勺\n老抽 1 勺\n淀粉 1 勺',
        'steps': '1. 牛肉切片，加生抽和淀粉腌 15 分钟。\n2. 热油滑炒牛肉至七成熟盛出。\n3. 大火热锅，下河粉快炒散开。\n4. 加老抽上色，倒回牛肉、豆芽、韭黄和洋葱丝。\n5. 大火翻炒 1 分钟，锅气出来就出锅。',
        'image_url': 'https://images.unsplash.com/photo-1552611052-33e04de081de?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'roast-goose',
        'name': '广式烧鹅',
        'category': '粤菜',
        'description': '皮脆肉嫩、汁水丰盈，蘸一口酸梅酱解腻提鲜。烧腊档口挂满的烧鹅，是广东人对美食的执念。',
        'ingredients': '光鹅 1 只\n五香粉 1 勺\n生抽 3 勺\n蚝油 2 勺\n麦芽糖 50 克\n白醋 2 勺\n盐 适量',
        'steps': '1. 鹅身擦干，用五香粉、生抽、蚝油、盐抹匀腌 4 小时。\n2. 麦芽糖加白醋和热水调成脆皮水。\n3. 腌好的鹅挂起，淋脆皮水后风干 2 小时。\n4. 烤箱 200 度烤 40 分钟至皮色红亮。\n5. 斩件装盘，配酸梅酱。',
        'image_url': 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'pineapple-bun',
        'name': '菠萝包',
        'category': '粤菜',
        'description': '酥皮像菠萝纹路，掰开夹一块黄油是港式茶餐厅的暗号。一杯丝袜奶茶一个菠萝包，就是半个香港的下午。',
        'ingredients': '高筋面粉 250 克\n酵母 3 克\n黄油 30 克\n低筋面粉 80 克\n糖粉 50 克\n鸡蛋 1 个\n奶粉 1 勺',
        'steps': '1. 高筋面粉加酵母、蛋液、黄油揉成面团，发酵 1 小时。\n2. 低筋面粉加糖粉、奶粉和黄油搓成酥皮，冷藏。\n3. 面团分剂揉圆，盖上压薄的酥皮，划出格子纹。\n4. 二次发酵 40 分钟，刷蛋液。\n5. 烤箱 180 度烤 15 分钟至表面金黄。',
        'image_url': 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'bobochicken',
        'name': '钵钵鸡',
        'category': '川菜',
        'description': '一钵红油冷汤，串串往里一涮就入味。乐山街头的钵钵鸡，辣而不燥，香得人一根接一根。',
        'ingredients': '鸡腿 2 个\n各种串串料（藕片、土豆片、木耳、毛肚等） 适量\n红油 3 勺\n花椒油 1 勺\n生抽 2 勺\n白糖 1 勺\n熟芝麻 1 勺',
        'steps': '1. 鸡腿煮熟撕成丝，素菜串串分别烫熟。\n2. 调汤：鸡汤加红油、花椒油、生抽、白糖拌匀。\n3. 串串和鸡丝放入冷汤中。\n4. 撒大量熟芝麻。\n5. 浸泡 30 分钟入味后开吃。',
        'image_url': 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'dandan-noodles',
        'name': '担担面',
        'category': '川菜',
        'description': '一小碗面，芝麻酱、红油、芽菜、肉臊层层叠叠，麻辣鲜香。四川人的温柔，就是提醒你『拌开再吃』。',
        'ingredients': '细面 150 克\n猪肉末 100 克\n芽菜 2 勺\n芝麻酱 1 勺\n红油 2 勺\n花椒粉 半勺\n生抽 1 勺\n花生碎 葱花 适量',
        'steps': '1. 热油炒香肉末，加芽菜和生抽炒成肉臊。\n2. 碗底放芝麻酱、红油、花椒粉和生抽。\n3. 面条煮熟捞入碗中。\n4. 铺上肉臊。\n5. 撒花生碎和葱花，拌匀开吃。',
        'image_url': 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'fuqi-feipian',
        'name': '夫妻肺片',
        'category': '川菜',
        'description': '牛头皮牛舌牛肚卤得透香，红油一浇，麻辣中带着回甜。一道菜能流传百年，靠的是真功夫，感情也是。',
        'ingredients': '牛腱 200 克\n牛肚 200 克\n牛舌 100 克\n卤料包 1 个\n红油 3 勺\n花椒粉 1 小勺\n生抽 2 勺\n白糖 1 勺\n花生碎 香菜 适量',
        'steps': '1. 牛腱、牛肚、牛舌分别焯水。\n2. 卤料包加水烧开，下三种牛杂卤 1 小时。\n3. 捞出晾凉切薄片，摆盘。\n4. 调汁：红油、花椒粉、生抽、白糖加卤汁拌匀。\n5. 浇汁撒花生碎和香菜。',
        'image_url': 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'wanzhou-grilled-fish',
        'name': '万州烤鱼',
        'category': '川菜',
        'description': '鱼烤得焦香，泡在咕嘟冒泡的红油里，配菜越煮越入味。重庆人的夜生活，从一条烤鱼和几瓶啤酒开始。',
        'ingredients': '草鱼 1 条\n洋葱 1 个\n土豆 莲藕 各 1 个\n豆瓣酱 3 勺\n干辣椒 10 个\n花椒 1 把\n孜然 1 勺\n啤酒 半罐',
        'steps': '1. 草鱼开背，抹盐、孜然和料酒腌 30 分钟。\n2. 烤箱 220 度烤 20 分钟至表面焦香。\n3. 热油炒香豆瓣酱、干辣椒和花椒。\n4. 加啤酒和配菜煮 5 分钟。\n5. 烤鱼装盘，连汁浇上，小火边煮边吃。',
        'image_url': 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'lion-head-meatball',
        'name': '扬州狮子头',
        'category': '江浙菜',
        'description': '肥瘦相间的肉球炖得入口即化，筷子轻轻一夹就散。淮扬菜的功夫菜，和慢工出细活的感情一样，急不得。',
        'ingredients': '五花肉 500 克\n荸荠 6 个\n鸡蛋 1 个\n姜末 葱末 适量\n生抽 2 勺\n料酒 2 勺\n淀粉 2 勺\n青菜 2 棵',
        'steps': '1. 五花肉细切粗斩成石榴粒大小，荸荠切碎。\n2. 肉粒加荸荠、蛋液、姜葱末、生抽料酒淀粉拌匀。\n3. 摔打上劲，团成大肉球。\n4. 砂锅垫菜叶，放肉球，加热水小火炖 2 小时。\n5. 加青菜烫熟即可。',
        'image_url': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'yangzhou-fried-rice',
        'name': '扬州炒饭',
        'category': '江浙菜',
        'description': '蛋香、虾仁、火腿、青豆，米粒在锅里跳舞，粒粒分明。一碗炒饭见功底，简单的东西做到极致最动人。',
        'ingredients': '隔夜米饭 2 碗\n鸡蛋 2 个\n虾仁 80 克\n火腿 50 克\n青豆 玉米粒 各 30 克\n葱花 适量\n盐 少许',
        'steps': '1. 鸡蛋打散，热油炒散盛出。\n2. 虾仁火腿切丁，与青豆玉米焯水。\n3. 大火热锅下米饭，炒散至粒粒分明。\n4. 加鸡蛋和配料丁，快速翻炒。\n5. 加盐调味，撒葱花出锅。',
        'image_url': 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'jianbing',
        'name': '煎饼果子',
        'category': '小吃',
        'description': '绿豆面摊成薄饼，磕个鸡蛋刷上酱，夹根油条卷起来。天津人的早晨，就藏在这套煎饼果子里。',
        'ingredients': '绿豆面 100 克\n面粉 50 克\n鸡蛋 2 个\n油条 2 根\n甜面酱 2 勺\n辣酱 1 勺\n葱花 香菜 适量\n黑芝麻 少许',
        'steps': '1. 绿豆面和面粉加水调成稀糊。\n2. 平底锅烧热，舀一勺面糊用竹刮子摊成圆薄饼。\n3. 磕一个鸡蛋摊开，撒葱花和黑芝麻。\n4. 翻面刷甜面酱和辣酱。\n5. 放油条卷起，中间折一刀装袋。',
        'image_url': 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'kaolengmian',
        'name': '烤冷面',
        'category': '东北菜',
        'description': '铁板上滋滋作响的冷面皮，刷酱打蛋卷火腿，是东北校门口的青春记忆。便宜又管饱，快乐就这么简单。',
        'ingredients': '冷面皮 2 张\n鸡蛋 2 个\n火腿肠 2 根\n洋葱碎 适量\n甜面酱 2 勺\n辣酱 1 勺\n香醋 1 勺\n白糖 半勺',
        'steps': '1. 平底锅刷油，放冷面皮小火煎软。\n2. 打一个鸡蛋摊在面皮上，撒洋葱碎。\n3. 鸡蛋凝固后翻面，刷甜面酱辣酱。\n4. 放煎好的火腿肠，撒糖和香醋。\n5. 卷起切段装盘。',
        'image_url': 'https://images.unsplash.com/photo-1552611052-33e04de081de?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'brown-sugar-ciba',
        'name': '红糖糍粑',
        'category': '甜品',
        'description': '糯米糍粑炸得外脆里糯，红糖浆一淋，黄豆粉一裹。川渝火锅的完美收尾，甜得刚刚好，像我们的日常。',
        'ingredients': '糯米粉 300 克\n红糖 80 克\n黄豆粉 50 克\n清水 适量\n食用油 适量',
        'steps': '1. 糯米粉加热水揉成团，搓成长条切段。\n2. 红糖加少许水熬成浓稠糖浆。\n3. 平底锅多油，下糍粑条小火煎至两面金黄。\n4. 煎好的糍粑摆盘。\n5. 淋红糖浆，撒黄豆粉。',
        'image_url': 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'osmanthus-fermented-rice',
        'name': '桂花酒酿',
        'category': '甜品',
        'description': '酒酿的清甜混着桂花香，再卧个水波蛋，是江南秋夜的温柔。微微的酒意，刚刚好的微醺。',
        'ingredients': '酒酿 300 克\n干桂花 1 小勺\n鸡蛋 1 个\n冰糖 20 克\n枸杞 几粒\n清水 300 毫升',
        'steps': '1. 锅中加水和冰糖煮开。\n2. 倒入酒酿小火煮 2 分钟。\n3. 打入鸡蛋，卧成水波蛋。\n4. 撒干桂花和枸杞。\n5. 关火焖 1 分钟，趁热喝。',
        'image_url': 'https://images.unsplash.com/photo-1558857563-b371033873b8?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'tanghulu',
        'name': '冰糖葫芦',
        'category': '小吃',
        'description': '山楂裹着透亮的冰糖壳，咬下去咔嚓一声，酸和甜一起在嘴里炸开。冬天的街头，最亮的那串红。',
        'ingredients': '山楂 20 颗\n冰糖 200 克\n清水 100 毫升\n竹签 5 根\n熟白芝麻 少许',
        'steps': '1. 山楂洗净去核，用竹签串成串。\n2. 冰糖加水，小火熬至糖浆浓稠冒细密小泡。\n3. 糖浆滴入冷水能迅速变脆即为合适。\n4. 山楂串快速在糖浆里滚一圈。\n5. 放在刷油的案板上晾凉定型。',
        'image_url': 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'corn-rib-soup',
        'name': '玉米排骨汤',
        'category': '家常菜',
        'description': '甜玉米和排骨炖出的清汤，鲜甜不腻。家常汤的意义不在惊艳，而在每天喝都不会腻，像细水长流的陪伴。',
        'ingredients': '肋排 500 克\n甜玉米 2 根\n胡萝卜 1 根\n姜 4 片\n料酒 2 勺\n盐 适量\n小葱 1 根',
        'steps': '1. 排骨冷水下锅焯水，撇净浮沫捞出。\n2. 玉米胡萝卜切段。\n3. 砂锅加水，放排骨、姜片和料酒，大火烧开。\n4. 转小火炖 40 分钟。\n5. 加玉米胡萝卜再炖 20 分钟，加盐撒葱花。',
        'image_url': 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'blanched-shrimp',
        'name': '白灼虾',
        'category': '粤菜',
        'description': '活虾沸水一烫，蘸姜葱酱油，鲜甜弹牙。粤菜白灼的哲学：好食材不需要复杂烹饪，真心也不需要花哨表达。',
        'ingredients': '基围虾 500 克\n姜 1 块\n小葱 2 根\n生抽 2 勺\n花生油 2 勺\n料酒 1 勺',
        'steps': '1. 基围虾剪须洗净。\n2. 锅中加水、姜片、葱结和料酒烧开。\n3. 下虾煮 2 分钟至变红卷曲。\n4. 捞出过一下冰水，摆盘。\n5. 姜葱切丝，加生抽淋热油做蘸料。',
        'image_url': 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'hk-milk-tea',
        'name': '港式奶茶',
        'category': '饮品',
        'description': '锡兰红茶撞入淡奶，丝袜般顺滑，茶香浓得恰到好处。香港茶餐厅的招牌，忙碌城市里的一口慢时光。',
        'ingredients': '锡兰红茶碎 30 克\n淡奶 150 毫升\n白糖 适量\n热水 600 毫升',
        'steps': '1. 红茶碎装入茶袋，冲入热水焖 8 分钟。\n2. 茶汤来回冲撞两次，撞出香气。\n3. 杯中加入淡奶。\n4. 高高冲入滚烫的茶汤。\n5. 按口味加糖，冷热皆宜。',
        'image_url': 'https://images.unsplash.com/photo-1558857563-b371033873b8?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'sour-plum-drink',
        'name': '酸梅汤',
        'category': '饮品',
        'description': '乌梅、山楂、甘草慢煮出的酸梅汤，冰镇后一口透心凉。老北京的消暑神器，酸酸甜甜赶走整个夏天。',
        'ingredients': '乌梅 30 克\n山楂 20 克\n甘草 5 克\n陈皮 5 克\n冰糖 80 克\n干桂花 少许\n清水 2 升',
        'steps': '1. 乌梅、山楂、甘草、陈皮洗净浸泡 30 分钟。\n2. 连水倒入锅中，大火烧开转小火煮 40 分钟。\n3. 加冰糖煮至融化。\n4. 滤出汤汁放凉，冰箱冷藏。\n5. 喝前撒干桂花。',
        'image_url': 'https://images.unsplash.com/photo-1558857563-b371033873b8?w=800&q=80&auto=format&fit=crop',
    },
    {
        'slug': 'hainan-chicken-rice',
        'name': '海南鸡饭',
        'category': '海南菜',
        'description': '皮滑肉嫩的鸡配鸡油饭，蘸上姜蓉、辣椒酱、黑酱油三色酱。南洋味道里的海南乡愁，简单却让人想念。',
        'ingredients': '三黄鸡 1 只\n香米 300 克\n鸡油 2 勺\n姜 1 块\n小葱 3 根\n黄瓜 1 根\n姜蓉酱 辣椒酱 黑酱油 各 1 碟',
        'steps': '1. 整鸡入锅，加水、姜葱小火浸煮 30 分钟。\n2. 捞出过冰水，斩件摆盘，配黄瓜片。\n3. 香米用鸡油炒香，加煮鸡的汤焖成饭。\n4. 鸡汤留一碗，加盐调成例汤。\n5. 配姜蓉酱、辣椒酱和黑酱油三碟蘸料。',
        'image_url': 'https://images.unsplash.com/photo-1562967914-608f82629710?w=800&q=80&auto=format&fit=crop',
    },
]
